[package]
name = "sitl"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
quick-xml = "0.25"

autopilot = { path = "../../autopilot" }
anyhow = "1.0.96"
