[package]
name = "sitl"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
quick-xml = "0.25"

autopilot = { path = "../../autopilot" }
anyhow = "1.0.96"
eframe = "0.31.0"
egui = "0.31.0"
env_logger = "0.11.6"
